spring.application.name=hotel-reservation-integration

# Porta exposta para a Render
server.port=${PORT:8080}

# Configurações do H2 Database (Em memória)
spring.datasource.url=jdbc:h2:mem:hotel_reservation
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilita o console do H2 no navegador (opcional, para você ver os dados)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

# Basic Auth
spring.security.user.name=${AUTH_USER:admin}
spring.security.user.password={noop}${AUTH_PASSWORD:123456}

# Scheduler
reservation.scheduler.delay=30000

# Mock endpoint
integration.omnibees.url=${OMNIBEES_URL:http://localhost:8080/mock/omnibees/reservations}
